export const profile = {
  name: "Ronit Madage",
  title: "Computer Engineering Student",
  subtitle: "Sardar Patel Institute of Technology (SPIT), Mumbai",
  tagline:
    "Building intelligent products, modern web applications, and AI-powered solutions for real-world problems.",
  email: "ronitmadage@gmail.com",
  github: "https://github.com/ronitmadage25-boop",
  linkedin: "https://www.linkedin.com/in/ronit-madage-92ab213b0/",
  location: "Mumbai, Maharashtra, India",
  about:
    "I'm Ronit Madage, a Computer Engineering student at Sardar Patel Institute of Technology (SPIT), Mumbai. I enjoy building modern web applications, exploring artificial intelligence, and creating software solutions that solve real-world problems. My interests span software engineering, AI-driven products, full-stack development, and user-centric digital experiences.",
  objective:
    "To become a highly skilled software professional who builds impactful products using modern technologies, artificial intelligence, and engineering best practices while continuously learning, innovating, and solving real-world challenges.",
};

export const education = {
  degree: "Bachelor of Engineering (Computer Engineering)",
  school: "Sardar Patel Institute of Technology (SPIT), Mumbai",
  description:
    "Currently pursuing a Bachelor's degree in Computer Engineering with a focus on software development, artificial intelligence, full-stack technologies, and modern engineering practices.",
};

export const experience = {
  role: "Web Development Intern",
  company: "V2V EdTech LLP",
  responsibilities: [
    "Developed responsive web interfaces using HTML, CSS, and JavaScript",
    "Worked on backend development using PHP",
    "Integrated MySQL databases",
    "Optimized website performance and usability",
    "Improved user experience through bug fixing and interface enhancements",
    "Collaborated on real-world software development projects",
  ],
};

export const skills = {
  languages: ["C", "C++", "Java", "Python", "PHP"],
  web: ["HTML5", "CSS3", "JavaScript", "MySQL", "SQLite"],
  tools: ["Git", "GitHub", "VS Code", "Android Studio"],
  core: [
    "Data Structures & Algorithms",
    "Object-Oriented Programming",
    "Database Management Systems",
    "Operating Systems",
    "Computer Networks",
  ],
};

export const projects = [
  {
    title: "CompressX",
    subtitle: "AI-Powered Image Optimization Platform",
    description:
      "An AI-powered image compression platform designed to intelligently reduce image size while maintaining visual quality, improving storage efficiency, faster sharing, and better web performance.",
    features: [
      "Intelligent image optimization",
      "Fast compression processing",
      "Quality preservation",
      "Modern responsive interface",
    ],
    link: "https://compressx-phi.vercel.app/",
    status: "Live",
  },
  {
    title: "Algoryx Mail AI Detector",
    subtitle: "AI Content Detection Platform",
    description:
      "Analyzes email and text content to estimate whether the content was generated by artificial intelligence or written by a human.",
    features: [
      "AI-generated content analysis",
      "Human-written content estimation",
      "Clean user interface",
      "Real-time analysis",
    ],
    link: "https://algoryxmail-ai.netlify.app/",
    status: "Live",
  },
  {
    title: "Farm To Market AI",
    subtitle: "Agricultural Intelligence Platform",
    description:
      "An AI-driven platform aimed at connecting farmers directly with markets to improve transparency, reduce intermediaries, and modernize agricultural commerce.",
    features: [],
    link: null,
    status: "In Development",
  },
];

export const interests = [
  "Artificial Intelligence",
  "Software Engineering",
  "Full-Stack Development",
  "Web Development",
  "Android Development",
  "Product Development",
  "Modern UI/UX Design",
  "Performance Optimization",
  "Open Source Technologies",
];
